#!/usr/bin/env python3
"""Deterministic verifier for task SpotHero--15 (generated by make_verifiers.py).

Ground truth is frozen from the reviewer's independent computation and live
honest walks on the review container (seed md5 482fb61d…). See
verify/README.md for the contract and task-specific caveats.
"""
import sys

from verify_lib import (Judge, check_package, check_seed_contract,
                        check_visited_path, check_visited_path_count,
                        check_answer_phrase,
                        check_answer_number, check_answer_any_number,
                        check_answer_any, check_only_tables_changed,
                        check_reservations_delta, check_any_new_reservation,
                        check_payment_methods_delta, check_profile_delta,
                        check_favorites_delta, check_new_user, final_answer,
                        run_verifier)

TASK_ID = "SpotHero--15"


def main(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_package(judge, traj, TASK_ID)
    check_seed_contract(judge, initial_db)
    check_visited_path(judge, traj, "login", r"/auth/login")
    check_visited_path(judge, traj, "millennium_facility_page", r"/facility/5284")
    check_visited_path(judge, traj, "union_square_search", r"/search\?.*search_string=Union")
    check_visited_path(judge, traj, "covered_filter", r"/search\?.*covered=1")
    check_visited_path(judge, traj, "riu_facility_page", r"/facility/6182")
    check_visited_path(judge, traj, "saved_spots_list", r"/account/favorites")
    check_answer_phrase(judge, answer, "spot_millennium", 'Millennium Park Garage')
    check_answer_phrase(judge, answer, "spot_park_millennium", 'Park Millennium Garage')
    check_answer_phrase(judge, answer, "spot_grant_park", 'Grant Park North')
    check_answer_phrase(judge, answer, "spot_riu", '280 Beach St')
    check_answer_number(judge, answer, "price_17", '17.00')
    check_answer_number(judge, answer, "price_14_97", '14.97')
    check_answer_number(judge, answer, "price_20", '20.00')
    check_answer_number(judge, answer, "price_12_07", '12.07')
    check_favorites_delta(judge, initial_db, after_db, user_id=1,
                          expect_pairs=[(1, 5284), (1, 104341), (1, 5283), (1, 6182)],
                          allow_readd=[(1, 5284)])
    check_only_tables_changed(judge, initial_db, after_db, ('favorites',))
    return judge


if __name__ == "__main__":
    sys.exit(run_verifier(TASK_ID, main))
