"""Per-task grading specs for the Statista review.

Ground truth is hardcoded here. ``tasks.jsonl`` carries rules only.
Numbers are accepted only as standalone tokens bound to their subject:
a swapped year, country, or market fails even when both figures appear.
"""

# groups: list of (subjects, competitors). The number or phrase must be
# nearer a subject than any competitor, within the default 220-character
# window (tighter windows are set on the window checks).

SPECS = {
    0: {
        "gates": [
            ("visited_statistic", r"/statistics/256598/"),
            ("visited_table", r"/statistics/256598/[^\s]*chart=table"),
            ("visited_favorites", r"/account/favorites"),
        ],
        "answers": [
            ("bound", "inflation_2025", "4.13", [(["2025"], ["2031", "2024", "2026"])]),
            ("bound", "inflation_2031", "3.2", [(["2031"], ["2025", "2024", "2026"])]),
            ("phrase", "saved", "favorites"),
        ],
        "state": {"allow_new_user": True, "fav_add": [(256598, None)]},
    },
    1: {
        "gates": [
            ("visited_statistic", r"/statistics/272014/"),
            ("visited_downloads", r"/account/downloads"),
        ],
        "answers": [
            ("bound", "facebook_users", "3070",
             [(["Facebook"], ["WhatsApp", "Instagram", "YouTube", "TikTok"])]),
            ("phrase", "png", "PNG"),
            ("phrase", "downloads", "download"),
        ],
        "state": {"allow_new_user": True,
                  "download": {"stat_id": 272014, "report_id": None, "fmt": "png"}},
    },
    2: {
        "gates": [
            ("visited_statistic", r"/statistics/268173/"),
            ("visited_favorites", r"/account/favorites"),
        ],
        "answers": [
            ("bound", "us_gdp", "32.38",
             [(["United States"], ["Germany", "China"])]),
            ("bound", "germany_gdp", "5.45",
             [(["Germany"], ["United States", "China"])]),
            ("bound", "gdp_gap", "26.93",
             [(["larger"], ["United States", "Germany", "China"])]),
            ("bound_phrase", "us_is_larger", "larger",
             [(["United States"], ["Germany", "China"])]),
            ("phrase", "saved", "favorites"),
        ],
        "state": {"allow_new_user": True, "fav_add": [(268173, None)]},
    },
    3: {
        "gates": [
            ("visited_login", r"/login"),
            ("visited_statistic", r"/statistics/267233/"),
            ("visited_favorites", r"/account/favorites"),
        ],
        "answers": [
            ("bound", "china_gw", "2258.02",
             [(["China"], ["United", "Brazil", "India", "Germany"])]),
            ("phrase", "saved", "favorites"),
        ],
        "state": {"email": "bob.c@test.com", "fav_add": [(267233, None)]},
    },
    4: {
        "gates": [
            ("visited_pricing", r"/pricing/"),
            ("visited_register", r"/register"),
            ("visited_account", r"/account"),
        ],
        "answers": [
            ("bound", "starter_price", "199",
             [(["Starter"], ["Personal", "Professional", "Basic"])]),
            ("bound", "personal_price", "649",
             [(["Personal"], ["Starter", "Professional", "Basic"])]),
            ("bound", "professional_price", "2388",
             [(["Professional"], ["Starter", "Personal", "Basic"])]),
            ("bound_phrase", "personal_previews", "previews",
             [(["Personal"], ["Professional", "Starter", "Basic"])]),
            ("phrase", "full_reports", "full reports"),
            ("phrase", "api", "API"),
            ("phrase", "basic_includes", "free statistics"),
            ("phrase", "member_since", "September 26, 2026"),
            ("phrase", "basic_type", "Basic"),
            ("bound", "favorites_zero", "0", [(["favorites"], ["downloads"])]),
            ("bound", "downloads_zero", "0", [(["downloads"], ["favorites"])]),
        ],
        "state": {"require_new_user": True, "email": "frank.miller@test.com",
                  "username": "frank_m"},
    },
    5: {
        "gates": [
            ("visited_consumer", r"/study/206237/"),
            ("visited_gaming", r"/study/123559/"),
        ],
        "answers": [
            ("bound", "consumer_pages", "37",
             [(["Consumer"], ["gaming", "video"])]),
            ("bound", "consumer_year", "2025",
             [(["Consumer"], ["gaming", "video"])]),
            ("bound", "consumer_price", "595",
             [(["Consumer"], ["gaming", "video"])]),
            ("bound", "gaming_pages", "62",
             [(["gaming"], ["Consumer"])]),
            ("bound", "gaming_year", "2026",
             [(["gaming"], ["Consumer"])]),
            ("bound", "gaming_price", "495",
             [(["gaming"], ["Consumer"])]),
            ("bound", "price_gap", "100",
             [(["more"], ["pages", "Consumer", "gaming"])]),
            ("phrase", "sentiment", "Consumer sentiment"),
            ("phrase", "optimism", "cautious optimism"),
            ("phrase", "tariffs", "tariffs"),
            ("phrase", "pptx", "PPTX"),
            ("phrase", "pdf", "PDF"),
            ("bound_phrase", "gaming_overview", "Overview",
             [(["gaming"], ["Consumer"])]),
            ("window", "gaming_longer", "longer", ["gaming"], ["Consumer"], 50),
        ],
        "state": None,
    },
    6: {
        "gates": [
            ("visited_outlook", r"/outlook/"),
            ("visited_mobility", r"/outlook/mobility-markets/"),
            ("visited_ride", r"/outlook/mmo/shared-mobility/ride-hailing/worldwide/"),
            ("visited_cars", r"/outlook/mmo/shared-mobility/car-rentals/worldwide/"),
        ],
        "answers": [
            ("bound", "ride_2026", "188.60",
             [(["ride-hailing"], ["car", "rentals"]), (["2026"], ["2030"])]),
            ("bound", "ride_2030_volume", "229.98",
             [(["ride-hailing"], ["car", "rentals"]), (["2030"], ["2026"]),
              (["volume"], ["users", "revenue"])]),
            ("bound", "ride_users", "2.34",
             [(["ride-hailing"], ["car", "rentals"]), (["users"], ["revenue", "volume"])]),
            ("bound", "ride_arpu", "96.95",
             [(["ride-hailing"], ["car", "rentals"])]),
            ("bound", "ride_china", "66",
             [(["China"], ["United"]), (["ride-hailing"], ["car", "rentals"])]),
            ("bound", "car_2026", "112.00",
             [(["car"], ["ride-hailing"]), (["2026"], ["2030"])]),
            ("bound", "car_2030_volume", "135.75",
             [(["car"], ["ride-hailing"]), (["2030"], ["2026"])]),
            ("bound", "car_users", "776.96",
             [(["car"], ["ride-hailing"]), (["users"], ["revenue", "volume"])]),
            ("bound", "car_arpu", "168.53",
             [(["car"], ["ride-hailing"])]),
            ("bound", "car_us", "34",
             [(["United States"], ["China"]), (["car"], ["ride-hailing"])]),
            ("window", "higher_revenue", "higher revenue",
             ["ride-hailing"], ["car"], 36),
            ("window", "higher_arpu", "higher average",
             ["car"], ["ride"], 36),
        ],
        "state": None,
    },
    7: {
        "gates": [
            ("visited_register", r"/register"),
            ("visited_statistic", r"/statistics/276629/"),
            ("visited_table", r"/statistics/276629/[^\s]*chart=table"),
            ("visited_favorites", r"/account/favorites"),
        ],
        "answers": [
            ("bound", "co2_2025", "38.11",
             [(["2025"], ["2024", "2023"])]),
            ("phrase", "saved", "favorites"),
        ],
        "state": {"require_new_user": True, "email": "casey.r@test.com",
                  "username": "casey_r", "fav_add": [(276629, None)]},
    },
    8: {
        "gates": [
            ("visited_statistic", r"/statistics/501853/"),
            ("visited_table", r"/statistics/501853/[^\s]*chart=table"),
        ],
        "answers": [
            ("bound", "cs2", "18.97",
             [(["Counter-Strike"], ["Dota", "Fortnite", "Rocket", "Legends", "Apex"])]),
            ("bound", "dota", "16.47",
             [(["Dota"], ["Counter-Strike", "Fortnite", "Rocket", "Apex"])]),
            ("bound", "fortnite", "12.91",
             [(["Fortnite"], ["Counter-Strike", "Dota", "Rocket", "Apex"])]),
            ("bound", "rocket", "8.5",
             [(["Rocket"], ["Legends", "Apex", "Fortnite", "Dota"])]),
            ("bound", "lol", "5.28",
             [(["Legends"], ["Rocket", "Apex", "Fortnite", "Dota"])]),
            ("bound", "apex", "5.0",
             [(["Apex"], ["Rocket", "Fortnite", "Dota"])]),
            ("bound", "ranked", "10", [(["games"], ["2025", "2026"])]),
            ("bound", "gap", "2.5",
             [(["bigger"], ["Counter-Strike", "Dota", "Fortnite", "Rocket", "Legends", "Apex"])]),
            ("phrase", "survey_start", "01/01/2025"),
            ("phrase", "survey_end", "31/12/2025"),
            ("phrase", "region", "Worldwide"),
            ("phrase", "label", "Total prize pool"),
        ],
        "state": None,
    },
    9: {
        "gates": [
            ("visited_inflation", r"/statistics/256598/"),
            ("visited_apa", r"/statistics/256598/[^\s]*citation=APA"),
            ("visited_mla", r"/statistics/256598/[^\s]*citation=MLA"),
            ("visited_co2_apa", r"/statistics/276629/[^\s]*citation=APA"),
        ],
        "answers": [
            ("phrase", "publisher", "Statista Research Department"),
            ("phrase", "inflation_url",
             "https://www.statista.com/statistics/256598/global-inflation-rate-compared-to-previous-year/"),
            ("phrase", "mla_date", "Aug 13, 2026"),
            ("phrase", "co2_apa_year", "(April 2026)"),
            ("phrase", "co2_url",
             "https://www.statista.com/statistics/276629/global-co2-emissions/"),
            ("phrase", "survey_start", "01/01/1980"),
            ("phrase", "survey_end", "31/12/2031"),
            ("phrase", "region", "Worldwide"),
        ],
        "state": None,
    },
    10: {
        "gates": [
            ("visited_topic", r"/topics/6077/"),
            ("visited_pick", r"/statistics/1299829/"),
        ],
        "answers": [
            ("bound", "users", "1.99", [(["users"], ["brand", "value"])]),
            ("bound", "brand", "75.67", [(["brand"], ["users"])]),
            ("bound", "duration", "42.7", [(["duration"], ["engagement", "brand"])]),
            ("bound", "engagement", "3.67", [(["engagement"], ["duration", "brand"])]),
            ("phrase", "indonesia", "Indonesia"),
            ("phrase", "creator", "Khabane Lame"),
            ("bound_phrase", "report_name", "TikTok",
             [(["titled", "report"], ["users", "brand", "creator"])]),
            ("phrase", "publisher", "Lionel Sujay Vailshery"),
            ("phrase", "published", "Jun 10, 2026"),
            ("phrase", "pick_update", "Jun 12, 2026"),
            ("phrase", "survey_start", "01/04/2026"),
            ("phrase", "survey_end", "30/04/2026"),
            ("phrase", "region", "Worldwide"),
            ("phrase", "label", "Share of population"),
        ],
        "state": None,
    },
    11: {
        "gates": [
            ("visited_login", r"/login"),
            ("visited_downloads", r"/account/downloads"),
            ("visited_favorites", r"/account/favorites"),
            ("visited_forecast", r"/forecasts/1474143/"),
        ],
        "answers": [
            ("phrase", "account_type", "Personal"),
            ("phrase", "latest_title", "Market size of AI"),
            ("phrase", "latest_fmt", "PNG"),
            ("phrase", "prior_title", "social networks"),
            ("phrase", "prior_fmt", "XLS"),
            ("bound", "download_count", "3",
             [(["downloads"], ["favorites", "2020", "2032"])]),
            ("bound", "fav_before", "5", [(["before"], ["after", "downloads"])]),
            ("bound", "fav_after", "4", [(["after"], ["before", "downloads"])]),
            ("phrase", "value_label", "billion U.S. dollars"),
            ("phrase", "removed", "removed the"),
        ],
        "state": {"email": "alice.j@test.com",
                  "fav_del": [(1, 1474143, None)]},
    },
    12: {
        "gates": [
            ("visited_statistic", r"/statistics/578364/"),
            ("visited_table", r"/statistics/578364/[^\s]*chart=table"),
        ],
        "answers": [
            ("bound", "india", "480.55",
             [(["India"], ["United States", "Brazil", "Indonesia", "Japan"])]),
            ("bound", "us", "181.75",
             [(["United States"], ["India", "Brazil", "Indonesia", "Japan"])]),
            ("bound", "brazil", "147.0",
             [(["Brazil"], ["India", "United States", "Indonesia", "Japan"])]),
            ("bound", "indonesia", "107.6",
             [(["Indonesia"], ["India", "Brazil", "Japan", "United States"])]),
            ("bound", "japan", "63.2",
             [(["Japan"], ["India", "Brazil", "Indonesia", "Turkey"])]),
            ("bound", "india_gap", "298.8",
             [(["larger"], ["India", "United States", "Brazil"])]),
            ("bound", "country_count", "20",
             [(["countries"], ["2025", "million", "October"])]),
            ("bound", "above_60", "6",
             [(["above"], ["India", "Japan", "2025", "October"])]),
            ("phrase", "threshold", "above 60"),
            ("phrase", "updated", "Oct 21, 2025"),
            ("phrase", "survey_start", "01/01/2025"),
            ("phrase", "survey_end", "31/12/2025"),
            ("phrase", "region", "Worldwide"),
            ("phrase", "label", "Audience in millions"),
        ],
        "state": None,
    },
    13: {
        "gates": [
            ("visited_reports_filter", r"content_type=Reports"),
            ("visited_study", r"/study/50485/"),
            ("visited_login", r"/login"),
            ("visited_favorites", r"/account/favorites"),
        ],
        "answers": [
            ("bound", "pages", "295", [(["pages"], ["1995", "costs", "price"])]),
            ("bound", "price", "1995", [(["costs", "price", "USD"], ["pages"])]),
            ("phrase", "released", "September 2025"),
            ("phrase", "first_entry", "Description"),
            ("phrase", "saved", "favorites"),
        ],
        "state": {"email": "carol.d@test.com", "fav_add": [(None, 50485)]},
    },
    14: {
        "gates": [
            ("visited_regions", r"/statistics/256626/"),
            ("visited_world", r"/statistics/256598/"),
        ],
        "answers": [
            ("bound", "ssa", "12.48",
             [(["Sub-Saharan"], ["European", "Union", "EU"])]),
            ("bound", "eu", "2.46",
             [(["European"], ["Sub-Saharan", "Africa"])]),
            ("bound", "times", "5.07",
             [(["times"], ["Sub-Saharan", "European", "Africa", "Union"])]),
            ("phrase", "regional_survey_start", "01/01/2025"),
            ("phrase", "regional_survey_end", "31/12/2025"),
            ("phrase", "regional_update", "Apr 15, 2026"),
            ("phrase", "regional_label", "Inflation rate compared with the previous year"),
            ("bound", "world_2025", "4.13",
             [(["2025"], ["2031", "2024"])]),
            ("bound", "world_2031", "3.2",
             [(["2031"], ["2025", "2024"])]),
            ("phrase", "world_survey_start", "01/01/1980"),
            ("phrase", "world_survey_end", "31/12/2031"),
            ("bound_phrase", "more_recent", "more recently",
             [(["worldwide", "average"], ["regional", "Sub-Saharan"])]),
        ],
        "state": None,
    },
    15: {
        "gates": [
            ("visited_login", r"/login"),
            ("visited_study", r"/study/206237/"),
            ("visited_downloads", r"/account/downloads"),
            ("visited_favorites", r"/account/favorites"),
        ],
        "answers": [
            ("bound", "pages", "37", [(["pages"], ["downloads", "price"])]),
            ("bound", "year", "2025", [(["Consumer"], ["PPT", "PDF"])]),
            ("bound", "price", "595", [(["price", "costs"], ["pages", "downloads"])]),
            ("phrase", "pdf", "PDF"),
            ("phrase", "prior", "renewable"),
            ("phrase", "prior_fmt", "PPT"),
            ("bound", "history_count", "6",
             [(["downloads"], ["pages", "price", "favorites"])]),
            ("phrase", "in_favorites", "favorites"),
        ],
        "state": {"email": "carol.d@test.com",
                  "download": {"stat_id": None, "report_id": 206237, "fmt": "pdf"}},
    },
    16: {
        "gates": [
            ("visited_statistic", r"/statistics/326017/"),
            ("visited_table", r"/statistics/326017/[^\s]*chart=table"),
        ],
        "answers": [
            ("bound", "brent_latest", "91.47",
             [(["Brent"], ["WTI", "OPEC"]), (["Jul 21"], ["Jul 14", "Apr 28"])]),
            ("bound", "wti_latest", "84.91",
             [(["WTI"], ["Brent", "OPEC"]), (["Jul 21"], ["Jul 14", "Apr 28"])]),
            ("bound", "opec_latest", "88.5",
             [(["OPEC"], ["Brent", "WTI"]), (["Jul 21"], ["Jul 14", "Apr 28"])]),
            ("bound", "brent_prior", "85.21",
             [(["Brent"], ["WTI", "OPEC"]), (["Jul 14"], ["Jul 21", "Apr 28"])]),
            ("bound", "wti_prior", "79.34",
             [(["WTI"], ["Brent", "OPEC"]), (["Jul 14"], ["Jul 21", "Apr 28"])]),
            ("bound", "opec_prior", "86.16",
             [(["OPEC"], ["Brent", "WTI"]), (["Jul 14"], ["Jul 21", "Apr 28"])]),
            ("bound", "brent_delta", "6.26",
             [(["Brent"], ["WTI", "OPEC"])]),
            ("bound", "wti_delta", "5.57",
             [(["WTI"], ["Brent", "OPEC"])]),
            ("bound", "opec_delta", "2.34",
             [(["OPEC"], ["Brent", "WTI"])]),
            ("bound", "brent_early", "104.53",
             [(["Brent"], ["WTI", "OPEC"]), (["Apr 28"], ["Jul 21", "Jul 14"])]),
            ("bound", "opec_early", "109.74",
             [(["OPEC"], ["Brent", "WTI"]), (["Apr 28"], ["Jul 21", "Jul 14"])]),
            ("bound", "wti_early", "99.93",
             [(["WTI"], ["Brent", "OPEC"]), (["Apr 28"], ["Jul 21", "Jul 14"])]),
            ("phrase", "survey_start", "January 6, 2020"),
            ("phrase", "survey_end", "July 21, 2026"),
            ("phrase", "updated", "July 2026"),
        ],
        "state": None,
    },
    17: {
        "gates": [
            ("visited_markets", r"/markets/"),
            ("visited_internet", r"/markets/424/internet/"),
            ("visited_us", r"/statistics/1044012/"),
            ("visited_shorts", r"/statistics/1314183/"),
            ("visited_social", r"/statistics/272014/"),
        ],
        "answers": [
            ("bound", "internet_users", "324",
             [(["internet"], ["social", "Facebook", "Shorts"])]),
            ("bound", "social_users", "254",
             [(["social"], ["internet", "Facebook", "Shorts"])]),
            ("bound", "user_gap", "70",
             [(["more"], ["Facebook", "WhatsApp", "Shorts"])]),
            ("phrase", "us_survey_start", "01/01/2025"),
            ("phrase", "us_survey_end", "31/12/2025"),
            ("phrase", "us_update", "Mar 18, 2026"),
            ("bound", "shorts_early", "1.5",
             [(["Jun"], ["Jul"]), (["Shorts", "YouTube"], ["internet", "Facebook"])]),
            ("bound_any", "shorts_later", ["2.0", "2"],
             [(["Jul"], ["Jun"]), (["Shorts", "YouTube"], ["internet", "Facebook"])]),
            ("phrase", "shorts_update", "Jul 26, 2023"),
            ("phrase", "shorts_survey_start", "01/06/2022"),
            ("phrase", "shorts_survey_end", "31/07/2023"),
            ("bound", "facebook", "3070",
             [(["Facebook"], ["WhatsApp", "Instagram", "YouTube"])]),
            ("bound", "second_network", "3000",
             [(["WhatsApp"], ["Facebook", "YouTube", "TikTok"])]),
        ],
        "state": None,
    },
    18: {
        "gates": [
            ("visited_statistic", r"/statistics/1294062/"),
            ("visited_table", r"/statistics/1294062/[^\s]*chart=table"),
        ],
        "answers": [
            ("bound", "pinterest", "67.3",
             [(["Pinterest"], ["TikTok", "Reddit", "Twitter", "Snapchat", "LinkedIn"])]),
            ("bound", "tiktok", "20.0",
             [(["TikTok"], ["Twitter", "Pinterest", "Reddit", "X"])]),
            ("bound", "reddit", "17.2",
             [(["Reddit"], ["TikTok", "Pinterest", "LinkedIn"])]),
            ("bound", "twitter_drop", "20.1",
             [(["Twitter"], ["TikTok", "Pinterest", "Reddit"])]),
            ("bound", "snapchat", "0.06",
             [(["Snapchat"], ["Pinterest", "TikTok", "Twitter"])]),
            ("bound", "platform_count", "9",
             [(["platforms"], ["2026", "Pinterest", "April"])]),
            ("bound_phrase", "smallest", "smallest",
             [(["Snapchat"], ["Pinterest", "TikTok", "Reddit", "Twitter"])]),
            ("bound_phrase", "shrank", "shrank",
             [(["Twitter"], ["Pinterest", "TikTok", "Reddit"])]),
            ("phrase", "fastest_names", "Pinterest"),
            ("phrase", "second_fast", "TikTok"),
            ("phrase", "third_fast", "Reddit"),
            ("phrase", "updated", "Jun 22, 2026"),
            ("phrase", "survey_start", "01/04/2026"),
            ("phrase", "survey_end", "30/04/2026"),
            ("phrase", "region", "Worldwide"),
            ("phrase", "label", "Growth"),
        ],
        "state": None,
    },
    19: {
        "gates": [
            ("visited_premium", r"/statistics/379046/"),
            ("visited_pricing", r"/pricing/"),
            ("visited_conversion", r"/statistics/439576/"),
        ],
        "answers": [
            ("phrase", "paid", "paid"),
            ("phrase", "starter_or_higher", "Starter Account or higher"),
            ("phrase", "exact", "exact figures"),
            ("bound_phrase", "ecommerce_update", "December",
             [(["retail", "commerce"], ["Switzerland", "conversion"])]),
            ("phrase", "ecommerce_region", "Worldwide"),
            ("phrase", "plans", "Personal"),
            ("phrase", "professional", "Professional"),
            ("phrase", "basic_excludes", "does not include premium"),
            ("bound", "cheapest", "199",
             [(["Starter"], ["Personal", "Professional", "Basic"])]),
            ("phrase", "basic_includes", "free statistics"),
            ("bound", "swiss", "2.4",
             [(["Switzerland"], ["Netherlands", "Germany", "United", "Global"]),
              (["Q2 '26"], ["Q2 '25", "Q3", "Q4"])]),
            ("bound_phrase", "swiss_update", "Aug",
             [(["Switzerland", "conversion"], ["retail", "commerce"])]),
        ],
        "state": None,
    },
    20: {
        "gates": [
            ("visited_login", r"/login"),
            ("visited_topic", r"/topics/3104/"),
            ("visited_pick", r"/forecasts/1474143/"),
            ("visited_favorites", r"/account/favorites"),
        ],
        "answers": [
            ("bound", "global_ai", "617.62",
             [(["global"], ["generative"])]),
            ("bound", "generative_ai", "63",
             [(["generative"], ["global"])]),
            ("phrase", "saved", "favorites"),
        ],
        "state": {"email": "david.k@test.com", "fav_add": [(1474143, None)]},
    },
    21: {
        "gates": [
            ("visited_contact", r"/contact/"),
            ("visited_gaming", r"/study/123559/"),
            ("visited_consumer", r"/study/206237/"),
        ],
        "answers": [
            ("bound", "gaming_price", "495",
             [(["gaming"], ["Consumer", "Trends"])]),
            ("bound", "gaming_pages", "62",
             [(["gaming"], ["Consumer"])]),
            ("bound", "gaming_year", "2026",
             [(["gaming"], ["Consumer"])]),
            ("bound_phrase", "overview", "Overview",
             [(["gaming"], ["Consumer"])]),
            ("bound", "consumer_price", "595",
             [(["Consumer"], ["gaming"])]),
            ("phrase", "thanks", "Thank you"),
            ("phrase", "received", "inquiry has been received"),
        ],
        "state": {"inquiry": {
            "name": "Dana White",
            "email": "dana.white@example.com",
            "needles": ["licensing", "gaming"],
        }},
    },
    22: {
        "gates": [
            ("visited_recent", r"/recent/statistics/"),
            ("visited_inflation", r"/statistics/256598/"),
            ("visited_co2", r"/statistics/276629/"),
        ],
        "answers": [
            ("bound_phrase", "inflation_date", "Aug",
             [(["inflation"], ["carbon", "dioxide", "CO2"])]),
            ("phrase", "inflation_full_date", "Aug 13, 2026"),
            ("bound_phrase", "co2_date", "April",
             [(["carbon", "dioxide"], ["inflation"])]),
            ("bound_phrase", "inflation_region", "Worldwide",
             [(["inflation"], ["carbon", "dioxide"])]),
            ("bound_phrase", "co2_region", "Worldwide",
             [(["carbon", "dioxide"], ["inflation"])]),
            ("bound_phrase", "more_recent", "more recently",
             [(["inflation"], ["carbon", "dioxide", "CO2"])]),
        ],
        "state": None,
    },
}
