#!/usr/bin/env python3
"""make_verifiers.py — deterministic generator for the trip_com verifier suite.

Writes one verify_<n>.py per task from the frozen SPECS table (hardcoded ground
truth, navigation gates, DB after-state templates). Regenerating must be
byte-identical: python3 make_verifiers.py && git diff --stat == clean.

Ground truth provenance: every value below was extracted from the reviewer's
independent container by honest Playwright walks of all 20 tasks plus direct
SQLite reads of the byte-reproducible seed. r2 re-freeze (2026-09-28): the
walks were re-run on the fixed site (contribution a375a671) in the r2
reviewer's own container; the deepened tasks' new asked facts were added as
purely additive answer checks, T17's booking row collapsed to the submitted
2026-10-12 date, T18 was unblocked (the form fix records the submitted date
and guests), and T6/T7/T12 navigation gates were relaxed to accept the URLs
real agent trajectories record (post-redirect pages and `+`-encoded query
strings).

Documented ties (graded as accepted sets):
  T2  — three $213 Delta nonstop SFO->JFK outbounds (ids 1/5/15, dep 07:00/
        16:15/22:15); the cheapest qualifying return is unique (id 149, $228).
  T11 — three $93 cheapest rooms at the Hyatt Place Miami Airport East (ids
        498/501/502); bed type and totals are identical across the tie; the
        runner-up Kompose also has a two-way $82 cheapest-room tie.
  T18 — three 5.0-rated Shanghai non-pass/non-tour activities; the task's
        "report the two top things its highlights section promises" resolves
        the tie to the only one with highlights (Shanghai imperial banquet).
Navigation-gate reality (r2): agent_demo records url_after = the page AFTER
each action, so form POSTs appear as their redirect targets. Gates for POST
actions (T6 cancel, T7 wishlist toggle) accept both the action URL and the
redirect target; T12's list gates accept both %20 and + space encodings
(url_for links produce %20, form GETs produce +).
Historical note (r1, resolved by the contribution fix 1e2ca971): the
attraction booking form's date/guests inputs were silently overridden by the
URL query string (request.values: args win), which made T18 BLOCKED and T17's
recorded date drift; the fix reads request.form first, and the r2 walks
confirm the submitted values are recorded (T17 2026-10-12, T18 3 guests on
2026-10-12 for $48.27).
"""
from pathlib import Path

HEADER = '''#!/usr/bin/env python3
"""Verify Trip.com--{n}.

{doc}

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_any, check_answer_count_at_least,
                        check_answer_money, check_answer_number, check_answer_phrase,
                        {blocked_import}check_only_tables_changed, check_read_only,
                        check_rows_added, check_rows_changed, check_seed_contract,
                        check_set_delta, check_screenshots, check_trajectory_identity,
                        check_visited_any, check_visited_path, final_answer, run_verifier)

TASK_ID = "Trip.com--{n}"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
{body}


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
'''

# ---------------------------------------------------------------------------
# Per-task specs. Keys:
#   doc      — one-line task summary for the module docstring
#   nav      — [(check_name, url_regex)] navigation gates
#   ans      — [(check_name, kind, value)] answer checks;
#              kind: phrase | any | number | money | count_ge | absent
#   db       — 'read_only' | ('only', {tables}) | list of (fn, args) DB checks
# ---------------------------------------------------------------------------
SPECS = {}

SPECS[0] = dict(
    doc="Deals promo -> Vegas 5-star <$250 with outdoor pool (Trump International) -> cheapest king room -> guest booking with TRIPNEW20 -> total $216.00.",
    nav=[("visited_deals", r"/deals/"),
         ("visited_hotel_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/737533"),
         ("visited_book_form", r"/hotels/book/54"),
         ("visited_confirmation", r"/hotels/confirmation/")],
    ans=[("answer_hotel", "phrase", "Trump International Hotel Las Vegas"),
         ("answer_king_room", "phrase", "Superior King Room"),
         ("answer_promo_code", "phrase", "TRIPNEW20"),
         ("answer_total", "money", 216.00)],
    db=[("check_rows_added", ("hotel_bookings",
         [["rx:^TH", 737533, 54, None, "Jordan", "Blake", "jordan.blake@example.com",
           "rx:\\+1 555 017 2222", "2026-10-04", "2026-10-05", 1, 2, 0,
           238.0, 32.0, 216.0, 2, "TRIPNEW20", "confirmed", None]],
         "hotel_booking_created")),
        ("check_only_tables_changed", ({"hotel_bookings"},))],
)

SPECS[1] = dict(
    doc="Two best-rated Vegas hotels <$150 free cancellation (Four Queens 8.7 / Planet Hollywood 8.5) -> book the cheaper one's lowest-priced room for 11-12 Oct -> total $82.00.",
    nav=[("visited_hotel_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/733224"),
         ("visited_book_form", r"/hotels/book/38"),
         ("visited_confirmation", r"/hotels/confirmation/")],
    ans=[("answer_picked_hotel", "phrase", "Planet Hollywood Resort & Casino"),
         ("answer_guest_score", "number", "8.5"),
         ("answer_total", "money", 82.00)],
    db=[("check_rows_added", ("hotel_bookings",
         [["rx:^TH", 733224, 38, None, "Dana", "Reyes", "dana.reyes@example.com",
           "rx:\\+1 555 013 3444", "2026-10-11", "2026-10-12", 1, 2, 0,
           72.0, 10.0, 82.0, 0, "", "confirmed", None]],
         "hotel_booking_created")),
        ("check_only_tables_changed", ({"hotel_bookings"},))],
)

SPECS[2] = dict(
    doc="SFO->JFK round trip 20/27 Oct, Delta, nonstop, cheapest qualifying: any of the three $213 outbounds + the $228 return 07:00 -> total $441.00.",
    nav=[("visited_flight_list", r"/flights/list\?"),
         ("visited_return_select", r"/flights/select/"),
         ("visited_book_form", r"/flights/book\?"),
         ("visited_confirmation", r"/flights/confirmation/")],
    ans=[("answer_airline", "phrase", "Delta"),
         ("answer_out_departure", "any", ["07:00", "16:15", "22:15"]),
         ("answer_return_departure", "phrase", "07:00"),
         ("answer_total", "money", 441.00)],
    db=[("check_rows_added", ("flight_bookings",
         [["rx:^TF", {1, 5, 15}, 149, None, "Maria", "Santos", "maria.santos@example.com",
           "rx:\\+1 555 014 4555", "Economy", "rt", 441.0, "", "confirmed", None]],
         "flight_booking_created")),
        ("check_only_tables_changed", ({"flight_bookings"},))],
)

SPECS[3] = dict(
    doc="Deals: cheapest of the six routes is SFO->LAS ($34) -> nonstop round trip 20/27 Oct: Frontier $34 out + Southwest $80 return -> total $114.00.",
    nav=[("visited_deals", r"/deals/"),
         ("visited_flight_list", r"/flights/list\?"),
         ("visited_return_select", r"/flights/select/"),
         ("visited_book_form", r"/flights/book\?"),
         ("visited_confirmation", r"/flights/confirmation/")],
    ans=[("answer_route", "any", ["San Francisco", "SFO"]),
         ("answer_airlines", "phrase", "Frontier"),
         ("answer_airlines2", "phrase", "Southwest"),
         ("answer_total", "money", 114.00)],
    db=[("check_rows_added", ("flight_bookings",
         [["rx:^TF", 859, 891, None, "Alex", "Moore", "alex.moore@example.com",
           "rx:\\+1 555 016 6677", "Economy", "rt", 114.0, "", "confirmed", None]],
         "flight_booking_created")),
        ("check_only_tables_changed", ({"flight_bookings"},))],
)

SPECS[4] = dict(
    doc="ORD->MIA one-way 22 Oct, nonstop, departs before noon: cheapest is American Airlines 08:43 for $169.",
    nav=[("visited_flight_list", r"/flights/list\?"),
         ("visited_book_form", r"/flights/book\?"),
         ("visited_confirmation", r"/flights/confirmation/")],
    ans=[("answer_airline", "phrase", "American"),
         ("answer_departure", "phrase", "08:43"),
         ("answer_price", "money", 169.00)],
    db=[("check_rows_added", ("flight_bookings",
         [["rx:^TF", 624, None, None, "Sam", "Patel", "sam.patel@example.com",
           "rx:\\+1 555 018 8888", "Economy", "ow", 169.0, "", "confirmed", None]],
         "flight_booking_created")),
        ("check_only_tables_changed", ({"flight_bookings"},))],
)

SPECS[5] = dict(
    doc="Orlando city-pass census (3 listed, cheapest Orlando: Go City Explorer Pass $60.84); best-rated pass <$70: Go City Orlando Explorer Pass (4.0, 1 review) -> book 2 guests for 6 Oct -> total $128.00; highest-rated Orlando experience of any kind: St. Augustine guided day trip (5.0).",
    nav=[("visited_orlando_list", r"/things-to-do/experiences/orlando"),
         ("visited_pass_detail", r"/things-to-do/detail/46680654"),
         ("visited_book_form", r"/things-to-do/book/1"),
         ("visited_confirmation", r"/things-to-do/confirmation/")],
    ans=[("answer_pass_name", "phrase", "Go City: Orlando Explorer Pass"),
         ("answer_rating", "number", "4.0"),
         ("answer_review_count", "number", "1"),
         ("answer_highlight_1", "phrase", "Save up to 50%"),
         ("answer_highlight_2", "any", ["30 days validity", "own pace"]),
         ("answer_validity", "phrase", "90 days"),
         ("answer_total", "money", 128.00),
         ("answer_passes_listed", "number", "3"),
         ("answer_cheapest_pass", "phrase", "Go City Explorer Pass"),
         ("answer_cheapest_price", "money", 60.84),
         ("answer_top_any_kind", "phrase", "St. Augustine"),
         ("answer_top_any_rating", "number", "5.0")],
    db=[("check_rows_added", ("attraction_bookings",
         [["rx:^TA", 46680654, 1, None, "2026-10-06", 2, "Pat", "Kim",
           "pat.kim@example.com", 128.0, "confirmed", None]],
         "attraction_booking_created")),
        ("check_only_tables_changed", ({"attraction_bookings"},))],
)

SPECS[6] = dict(
    doc="Alice: 480 Trip Coins, hotel THALICE1 at Harrah's Las Vegas (check-in 16:00), flight TFALICE1 SFO->JFK out 22:15 / return 11:35; wishlist 3 saved (priciest $327); FLYTRIP10 min $150; nonstop rebooking on the route $205+$228=$433; cancel the more expensive booking (the flight, $422).",
    nav=[("visited_sign_in", r"/sign-in/"),
         ("visited_account", r"/account/"),
         ("visited_bookings", r"/account/bookings"),
         ("visited_hotel_page", r"/hotels/detail/718690"),
         ("visited_cancel", [r"/bookings/cancel/flight/TFALICE1", r"/account/bookings"])],
    ans=[("answer_coins", "number", "480"),
         ("answer_hotel", "phrase", "Harrah"),
         ("answer_checkin_time", "phrase", "16:00"),
         ("answer_route", "any", ["SFO", "San Francisco"]),
         ("answer_outbound_time", "phrase", "22:15"),
         ("answer_cancelled_ref", "phrase", "TFALICE1"),
         ("answer_flight_status", "phrase", "cancelled"),
         ("answer_hotel_status", "phrase", "confirmed"),
         ("answer_wishlist_count", "number", "3"),
         ("answer_priciest", "number", "327"),
         ("answer_promo_min", "number", "150"),
         ("answer_rebook_total", "money", 433.00)],
    db=[("check_rows_changed", ("flight_bookings",
         [["TFALICE1", 1, 2, 1, "Alice", "Johnson", "alice.j@test.com",
           "rx:\\+1 555 010 0000", "Economy", "rt", 422.0, "", "cancelled", None]],
         "flight_cancelled")),
        ("check_only_tables_changed", ({"flight_bookings"},))],
)

SPECS[7] = dict(
    doc="Bob: save best-rated SF hotel <$200 (Hotel Fiona, 8.6, $187) to wishlist; remove the more expensive of the two saved Vegas hotels (Thunderbird $57); remaining: Hotel 32One $212, Hotel Fiona $187, Horseshoe $56.",
    nav=[("visited_sign_in", r"/sign-in/"),
         ("visited_wishlist", r"/account/wishlist"),
         ("visited_sf_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/715700"),
         ("visited_wishlist_toggle", [r"/wishlist/toggle/715700", r"/hotels/detail/715700"])],
    ans=[("answer_fiona", "phrase", "Hotel Fiona"),
         ("answer_fiona_price", "number", "187"),
         ("answer_32one", "phrase", "Hotel 32One"),
         ("answer_32one_price", "number", "212"),
         ("answer_horseshoe", "phrase", "Horseshoe"),
         ("answer_horseshoe_price", "number", "56")],
    db=[("check_set_delta", ("wishlist_items", ["user_id", "hotel_id"],
         [[2, 714958]], [[2, 715700]], "wishlist_set_delta")),
        ("check_only_tables_changed", ({"wishlist_items"},))],
)

SPECS[8] = dict(
    doc="TRIPNEW20 min spend $100 -> cheapest Paris Las Vegas room (Room Type Assigned On Arrival, $167/$189) for 4-5 Oct -> discount $37.80, final total $151.20.",
    nav=[("visited_deals", r"/deals/"),
         ("visited_hotel_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/733090"),
         ("visited_book_form", r"/hotels/book/22"),
         ("visited_confirmation", r"/hotels/confirmation/")],
    ans=[("answer_min_spend", "number", "100"),
         ("answer_room", "phrase", "Room Type Assigned On Arrival"),
         ("answer_discount", "money", 37.80),
         ("answer_total", "money", 151.20),
         ("answer_promo", "phrase", "TRIPNEW20")],
    db=[("check_rows_added", ("hotel_bookings",
         [["rx:^TH", 733090, 22, None, "Robin", "Fox", "robin.fox@example.com",
           "rx:\\+1 555 019 9900", "2026-10-04", "2026-10-05", 1, 2, 0,
           167.0, 22.0, 151.2, 1, "TRIPNEW20", "confirmed", None]],
         "hotel_booking_created")),
        ("check_only_tables_changed", ({"hotel_bookings"},))],
)

SPECS[9] = dict(
    doc="NY weekend guide: Jersey City and Newark rates 30-40% lower; NY hotels >500 reviews + parking ranked by score: Motto by Hilton NYC Times Square (8.7, 714 reviews; tags 'American breakfast'/'Great views'; cheapest room Flex Room With Wall Bed $202/$236, queen, no breakfast, free cancellation before 11:59 PM Oct 1, taxes $34/night on the booking form) vs DoubleTree by Hilton New York Downtown (8.4, cheapest room King Room With City View $175). Read-only.",
    nav=[("visited_guide", r"/guide/nyc-weekend-midrange"),
         ("visited_hotel_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/105237897"),
         ("visited_book_form", r"/hotels/book/124"),
         ("visited_second_hotel", r"/hotels/detail/2192841")],
    ans=[("answer_hotel", "phrase", "Motto by Hilton New York City Times Square"),
         ("answer_score", "number", "8.7"),
         ("answer_reviews", "number", "714"),
         ("answer_tag_1", "phrase", "American breakfast"),
         ("answer_tag_2", "phrase", "Great views"),
         ("answer_room", "phrase", "Flex Room With Wall Bed"),
         ("answer_room_price", "money", 202.00),
         ("answer_bed", "phrase", "queen"),
         ("answer_breakfast", "phrase", "breakfast"),
         ("answer_cancel_deadline", "phrase", "11:59 PM, Oct 1"),
         ("answer_guide_discount", "phrase", "30-40%"),
         ("answer_second_hotel", "phrase", "DoubleTree"),
         ("answer_second_score", "number", "8.4"),
         ("answer_taxes_per_night", "money", 34.00),
         ("answer_other_room", "phrase", "King Room With City View"),
         ("answer_other_price", "money", 175.00)],
    db="read_only",
)

SPECS[10] = dict(
    doc="Orlando guide: 2 days per major park; cheapest city pass (Go City Explorer Pass, $60.84) for 2 people 6 Oct -> total $121.68.",
    nav=[("visited_guide", r"/guide/orlando-theme-park-planning"),
         ("visited_orlando_list", r"/things-to-do/experiences/orlando"),
         ("visited_pass_detail", r"/things-to-do/detail/110625321"),
         ("visited_book_form", r"/things-to-do/book/2"),
         ("visited_confirmation", r"/things-to-do/confirmation/")],
    ans=[("answer_guide_days", "phrase", "2 days per major park"),
         ("answer_pass", "phrase", "Go City Explorer Pass"),
         ("answer_total", "money", 121.68)],
    db=[("check_rows_added", ("attraction_bookings",
         [["rx:^TA", 110625321, 2, None, "2026-10-06", 2, "Mel", "Wu",
           "mel.wu@example.com", 121.68, "confirmed", None]],
         "attraction_booking_created")),
        ("check_only_tables_changed", ({"attraction_bookings"},))],
)

SPECS[11] = dict(
    doc="Carol: 480 Trip Coins; two cheapest bookable Miami hotels: Hyatt Place Miami Airport East (8.3, $93; cheapest room $93/$105 incl. taxes, $1.05 Trip Coins, 1 king bed and 1 sofa bed) and Kompose Boutique Hotel Miami Airport (8.3, $100; cheapest room $82); wishlist 3 saved; highest-minimum coupon SAVE25 ($200). Read-only.",
    nav=[("visited_sign_in", r"/sign-in/"),
         ("visited_account", r"/account/"),
         ("visited_hotel_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/4648397"),
         ("visited_runnerup_detail", r"/hotels/detail/68493916"),
         ("visited_wishlist", r"/account/wishlist"),
         ("visited_coupons", r"/account/coupons")],
    ans=[("answer_coins", "number", "480"),
         ("answer_hotel", "phrase", "Hyatt Place Miami Airport East"),
         ("answer_score", "number", "8.3"),
         ("answer_room_name", "any",
          ["King Room", "Accessible King Bed/Tub", "Accessible King Room With Sofa Bed"]),
         ("answer_bed", "phrase", "1 king bed and 1 sofa bed"),
         ("answer_room_total", "money", 105.00),
         ("answer_coins_earned", "money", 1.05),
         ("answer_runnerup", "phrase", "Kompose"),
         ("answer_runnerup_score", "number", "8.3"),
         ("answer_runnerup_price", "money", 100.00),
         ("answer_runnerup_room", "phrase", "King Room"),
         ("answer_runnerup_room_price", "money", 82.00),
         ("answer_wishlist_count", "number", "3"),
         ("answer_coupon", "phrase", "SAVE25"),
         ("answer_coupon_min", "number", "200")],
    db="read_only",
)

SPECS[12] = dict(
    doc="Cheapest available hotel per city 4-5 Oct: Vegas Harrah's Las Vegas ($56, 8.4, 5 room choices) vs NY HI New York City Hostel ($104, 9.0, 2 room choices); Vegas cheaper by $48. Read-only.",
    nav=[("visited_vegas_list", [r"/hotels/list\?city=Las%20Vegas", r"/hotels/list\?city=Las\+Vegas"]),
         ("visited_vegas_detail", r"/hotels/detail/718690"),
         ("visited_ny_list", [r"/hotels/list\?city=New%20York", r"/hotels/list\?city=New\+York"]),
         ("visited_ny_detail", r"/hotels/detail/2092657")],
    ans=[("answer_vegas_hotel", "phrase", "Harrah"),
         ("answer_vegas_price", "number", "56"),
         ("answer_vegas_score", "number", "8.4"),
         ("answer_vegas_rooms", "number", "5"),
         ("answer_ny_hotel", "phrase", "HI New York City Hostel"),
         ("answer_ny_price", "number", "104"),
         ("answer_ny_score", "number", "9.0"),
         ("answer_ny_rooms", "number", "2"),
         ("answer_cheaper_city", "phrase", "Vegas"),
         ("answer_difference", "number", "48")],
    db="read_only",
)

SPECS[13] = dict(
    doc="Best-rated bookable Vegas hotel <$120 off-Strip for 13-14 Oct: Four Queens Hotel and Casino (8.7, $104, 3-star, Downtown - Fremont Street; cheapest room Run Of House Room, free cancellation before 11:59 PM Oct 1, booking-form grand total $73.00 for the one night); best-rated bookable Strip hotel <$120: Planet Hollywood Resort & Casino (8.5, $72, cheapest room Room Type Assigned On Arrival). Read-only.",
    nav=[("visited_hotel_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/718623"),
         ("visited_book_form", r"/hotels/book/30"),
         ("visited_strip_detail", r"/hotels/detail/733224")],
    ans=[("answer_hotel", "phrase", "Four Queens Hotel and Casino"),
         ("answer_area", "phrase", "Downtown - Fremont Street"),
         ("answer_score", "number", "8.7"),
         ("answer_price", "number", "104"),
         ("answer_stars", "number", "3"),
         ("answer_cancel_deadline", "phrase", "11:59 PM, Oct 1"),
         ("answer_grand_total", "money", 73.00),
         ("answer_strip_hotel", "phrase", "Planet Hollywood"),
         ("answer_strip_score", "number", "8.5"),
         ("answer_strip_price", "money", 72.00),
         ("answer_strip_room", "phrase", "Room Type Assigned On Arrival")],
    db="read_only",
)

SPECS[14] = dict(
    doc="MIA->NY round trip 24/31 Oct cheapest ($130 + $81 = $211) with FLYTRIP10 (10% off, min $150): discount $21.10, total paid $189.90.",
    nav=[("visited_deals", r"/deals/"),
         ("visited_flight_list", r"/flights/list\?"),
         ("visited_return_select", r"/flights/select/"),
         ("visited_book_form", r"/flights/book\?"),
         ("visited_confirmation", r"/flights/confirmation/")],
    ans=[("answer_promo", "phrase", "FLYTRIP10"),
         ("answer_discount", "money", 21.10),
         ("answer_total", "money", 189.90)],
    db=[("check_rows_added", ("flight_bookings",
         [["rx:^TF", 783, 852, None, "Jamie", "Lee", "jamie.lee@example.com",
           "rx:\\+1 555 015 5566", "Economy", "rt", 189.9, "FLYTRIP10", "confirmed", None]],
         "flight_booking_created")),
        ("check_only_tables_changed", ({"flight_bookings"},))],
)

SPECS[15] = dict(
    doc="David: 480 Trip Coins; bookings Harrah's Las Vegas Nov 1-3 $136 (136 Trip Coins) + Orlando Go City Explorer Pass Nov 2 $121.68; hotel page: 8.4, 3-star, Las Vegas Strip, check-in 16:00, cheapest room $56; that room's repeat two-night total 18-20 Nov $128.00; booked activity found via site search (highlights: choose 2 to 5 attractions); wishlist 3 saved; ACTIVITY15 min $50. Read-only.",
    nav=[("visited_sign_in", r"/sign-in/"),
         ("visited_account", r"/account/"),
         ("visited_bookings", r"/account/bookings"),
         ("visited_hotel_page", r"/hotels/detail/718690"),
         ("visited_repeat_form", r"/hotels/book/1"),
         ("visited_search", r"/search\?"),
         ("visited_activity_detail", r"/things-to-do/detail/110625321"),
         ("visited_wishlist", r"/account/wishlist"),
         ("visited_coupons", r"/account/coupons")],
    ans=[("answer_coins", "number", "480"),
         ("answer_hotel_booking", "phrase", "Harrah"),
         ("answer_hotel_dates", "phrase", "Nov 1"),
         ("answer_hotel_total", "money", 136.00),
         ("answer_attraction_booking", "phrase", "Go City Explorer Pass"),
         ("answer_attraction_total", "money", 121.68),
         ("answer_stars", "number", "3"),
         ("answer_area", "phrase", "Las Vegas Strip"),
         ("answer_cheapest_room", "phrase", "Room Type Assigned On Arrival"),
         ("answer_room_price", "number", "56"),
         ("answer_coins_earned", "number", "136"),
         ("answer_checkin_time", "phrase", "16:00"),
         ("answer_repeat_total", "money", 128.00),
         ("answer_highlights_choose", "phrase", "Choose 2 to 5"),
         ("answer_wishlist_count", "number", "3"),
         ("answer_coupon", "phrase", "ACTIVITY15"),
         ("answer_coupon_min", "number", "50")],
    db="read_only",
)

SPECS[16] = dict(
    doc="Paris Las Vegas two nights 5-7 Oct in the cheapest room: $167 nightly, $22 taxes/fees per night, $378 grand total; room sleeps 2, 1 king or 2 queen, free cancellation before 11:59 PM Oct 1; second-cheapest room Bordeaux Room King grand total $388; cheapest room one-night total 5-6 Oct $189; hotel 8.6 with 805 reviews; site search shows Bellagio at $467. Read-only (booking forms opened to confirm, no booking made).",
    nav=[("visited_search", r"/search\?"),
         ("visited_hotel_detail", r"/hotels/detail/733090"),
         ("visited_book_form", r"/hotels/book/(22|24)")],
    ans=[("answer_nightly", "money", 167.00),
         ("answer_taxes_per_night", "money", 22.00),
         ("answer_grand_total", "money", 378.00),
         ("answer_room", "phrase", "Room Type Assigned On Arrival"),
         ("answer_bed", "phrase", "1 king bed or 2 queen beds"),
         ("answer_sleeps", "number", "2"),
         ("answer_cancel_deadline", "phrase", "11:59 PM, Oct 1"),
         ("answer_second_room", "phrase", "Bordeaux Room King"),
         ("answer_second_total", "money", 388.00),
         ("answer_onenight_total", "money", 189.00),
         ("answer_score", "number", "8.6"),
         ("answer_reviews", "number", "805"),
         ("answer_bellagio", "phrase", "Bellagio"),
         ("answer_bellagio_rate", "money", 467.00)],
    db="read_only",
)

SPECS[17] = dict(
    doc="Hong Kong: 4 categories with activities (Activities/City passes/Tickets/Tours), 35 experiences, 18 tours via the category filter, cheapest Hung Fook Tong e-voucher $1.15; most-booked Top-Rated Hong Kong Tour ($76.52, 27 reviews, 610 booked; both top-two packages valid 90 days) booked for 2 people on 12 October -> total $153.04 (form fix: the submitted 12 Oct date is now recorded).",
    nav=[("visited_hk_list", r"/things-to-do/experiences/hong_kong"),
         ("visited_tour_detail", r"/things-to-do/detail/94229569"),
         ("visited_book_form", r"/things-to-do/book/41"),
         ("visited_confirmation", r"/things-to-do/confirmation/")],
    ans=[("answer_categories", "count_ge",
          (["Activities", "City passes", "Tickets", "Tours"], 4)),
         ("answer_total_experiences", "number", "35"),
         ("answer_tours_count", "number", "18"),
         ("answer_cheapest", "phrase", "Hung Fook Tong"),
         ("answer_cheapest_price", "money", 1.15),
         ("answer_most_booked", "phrase", "Top-Rated Hong Kong Tour"),
         ("answer_reviews", "number", "27"),
         ("answer_booked_count", "number", "610"),
         ("answer_total_paid", "money", 153.04)],
    db=[("check_rows_added", ("attraction_bookings",
         [["rx:^TA", 94229569, 41, None, "2026-10-12", 2, "Leo", "Ng",
           "leo.ng@example.com", 153.04, "confirmed", None]],
         "attraction_booking_created")),
        ("check_only_tables_changed", ({"attraction_bookings"},))],
)

SPECS[18] = dict(
    doc="Shanghai census (35 listed, 14 in Activities, 4 share the 5.0 top rating); highest-rated non-pass non-tour: Shanghai imperial banquet (5.0, 36 reviews, 652 booked; highlights: Shuyanfu immersive ritual/music culture + dishes that surprise your taste buds; package valid 90 days) booked for 3 guests on 12 October -> total $48.27 (form fix: the submitted date/guests are now recorded).",
    nav=[("visited_shanghai_list", r"/things-to-do/experiences/shanghai"),
         ("visited_activity_detail", r"/things-to-do/detail/99290859"),
         ("visited_book_form", r"/things-to-do/book/110"),
         ("visited_confirmation", r"/things-to-do/confirmation/")],
    ans=[("answer_activity", "phrase", "Shanghai imperial banquet"),
         ("answer_rating", "number", "5.0"),
         ("answer_highlight_1", "phrase", "Shuyanfu"),
         ("answer_highlight_2", "phrase", "taste buds"),
         ("answer_total_paid", "money", 48.27),
         ("answer_total_listed", "number", "35"),
         ("answer_activities_count", "number", "14"),
         ("answer_top_rating_shared", "number", "4"),
         ("answer_review_count", "number", "36"),
         ("answer_booked_count", "number", "652"),
         ("answer_validity", "phrase", "90 days")],
    db=[("check_rows_added", ("attraction_bookings",
         [["rx:^TA", 99290859, 110, None, "2026-10-12", 3, "Wei", "Chen",
           "wei.chen@example.com", "rx:^48\\.2(69|7)", "confirmed", None]],
         "attraction_booking_created")),
        ("check_only_tables_changed", ({"attraction_bookings"},))],
)

SPECS[19] = dict(
    doc="Free-cancellation guide: refundable rates commonly allow cancelling before 11:59 PM local hotel time one to three days before check-in (after the deadline you are charged the first night or the full amount); cheapest bookable Vegas hotels <$60 for 20-21 Oct: Harrah's Las Vegas (8.4, 536 reviews, Las Vegas Strip, parking amenity, cheapest room free cancellation before 11:59 PM Oct 1, booking-form total $64.00 for the night) and The LINQ (8.4, 344 reviews, cheapest room Deluxe Two Double Room Non smoking). Read-only.",
    nav=[("visited_search", r"/search\?"),
         ("visited_guide", r"/guide/free-cancellation-guide"),
         ("visited_hotel_list", r"/hotels/list\?"),
         ("visited_hotel_detail", r"/hotels/detail/718690"),
         ("visited_book_form", r"/hotels/book/1"),
         ("visited_linq_detail", r"/hotels/detail/1775443")],
    ans=[("answer_guide_deadline", "phrase", "11:59 PM"),
         ("answer_guide_window", "phrase", "one to three days"),
         ("answer_guide_after", "phrase", "first night"),
         ("answer_hotel", "phrase", "Harrah"),
         ("answer_score", "number", "8.4"),
         ("answer_reviews", "number", "536"),
         ("answer_cancel_deadline", "phrase", "11:59 PM, Oct 1"),
         ("answer_runnerup", "phrase", "LINQ"),
         ("answer_runnerup_reviews", "number", "344"),
         ("answer_runnerup_room", "phrase", "Deluxe Two Double Room"),
         ("answer_area", "phrase", "Las Vegas Strip"),
         ("answer_parking", "phrase", "parking"),
         ("answer_room_total", "money", 64.00)],
    db="read_only",
)


def render_answer_check(check, kind, value):
    if kind == "phrase":
        return f'    check_answer_phrase(judge, answer, "{check}", {value!r})'
    if kind == "any":
        return f'    check_answer_any(judge, answer, "{check}", {value!r})'
    if kind == "number":
        return f'    check_answer_number(judge, answer, "{check}", {value!r})'
    if kind == "money":
        return f'    check_answer_money(judge, answer, "{check}", {value!r})'
    if kind == "count_ge":
        opts, minimum = value
        return (f'    check_answer_count_at_least(judge, answer, "{check}", '
                f'{opts!r}, {minimum!r})')
    if kind == "absent":
        return f'    check_answer_absent(judge, answer, "{check}", {value!r})'
    raise ValueError(kind)


def render_db_check(spec):
    if spec == "read_only":
        return ["    check_read_only(judge, initial_db, after_db)"]
    lines = []
    for fn, args in spec:
        if fn == "check_rows_added":
            table, templates, check = args
            lines.append(f'    check_rows_added(judge, initial_db, after_db, {table!r},')
            lines.append(f'                      {templates!r}, {check!r})')
        elif fn == "check_rows_changed":
            table, templates, check = args
            lines.append(f'    check_rows_changed(judge, initial_db, after_db, {table!r},')
            lines.append(f'                       {templates!r}, {check!r})')
        elif fn == "check_set_delta":
            table, key_cols, removed, added, check = args
            lines.append(f'    check_set_delta(judge, initial_db, after_db, {table!r},')
            lines.append(f'                    {key_cols!r}, {removed!r}, {added!r}, {check!r})')
        elif fn == "check_only_tables_changed":
            lines.append(f'    check_only_tables_changed(judge, initial_db, after_db, {args[0]!r})')
        elif fn == "check_blocked":
            check, note = args
            note_line = " ".join(note.split())
            lines.append(f'    check_blocked(judge, {check!r},')
            lines.append(f'                 {note_line!r})')
        else:
            raise ValueError(fn)
    return lines


def main():
    out_dir = Path(__file__).resolve().parent
    for n, spec in sorted(SPECS.items()):
        body = []
        for check, pattern in spec["nav"]:
            if isinstance(pattern, (list, tuple)):
                # multi-pattern gate: a real agent trajectory may record either
                # the form-action URL or the post-redirect URL (agent_demo
                # records url_after = post-redirect page).
                body.append(f'    check_visited_any(judge, traj, "{check}", {pattern!r})')
            else:
                body.append(f'    check_visited_path(judge, traj, "{check}", r"{pattern}")')
        for check, kind, value in spec["ans"]:
            body.append(render_answer_check(check, kind, value))
        body += render_db_check(spec["db"])
        blocked_import = "check_blocked, " if (
            isinstance(spec["db"], list) and any(
                fn == "check_blocked" for fn, _ in spec["db"])) else ""
        text = HEADER.format(n=n, doc=spec["doc"], body="\n".join(body),
                             blocked_import=blocked_import)
        (out_dir / f"verify_{n}.py").write_text(text, encoding="utf-8")
    print(f"wrote {len(SPECS)} verifiers to {out_dir}")


if __name__ == "__main__":
    main()
