#!/usr/bin/env python3
"""Verify Trip.com--17.

Hong Kong: 4 categories with activities (Activities/City passes/Tickets/Tours), 35 experiences, 18 tours via the category filter, cheapest Hung Fook Tong e-voucher $1.15; most-booked Top-Rated Hong Kong Tour ($76.52, 27 reviews, 610 booked; both top-two packages valid 90 days) booked for 2 people on 12 October -> total $153.04 (form fix: the submitted 12 Oct date is now recorded).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_any, check_answer_count_at_least,
                        check_answer_money, check_answer_number, check_answer_phrase,
                        check_only_tables_changed, check_read_only,
                        check_rows_added, check_rows_changed, check_seed_contract,
                        check_set_delta, check_screenshots, check_trajectory_identity,
                        check_visited_any, check_visited_path, final_answer, run_verifier)

TASK_ID = "Trip.com--17"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_hk_list", r"/things-to-do/experiences/hong_kong")
    check_visited_path(judge, traj, "visited_tour_detail", r"/things-to-do/detail/94229569")
    check_visited_path(judge, traj, "visited_book_form", r"/things-to-do/book/41")
    check_visited_path(judge, traj, "visited_confirmation", r"/things-to-do/confirmation/")
    check_answer_count_at_least(judge, answer, "answer_categories", ['Activities', 'City passes', 'Tickets', 'Tours'], 4)
    check_answer_number(judge, answer, "answer_total_experiences", '35')
    check_answer_number(judge, answer, "answer_tours_count", '18')
    check_answer_phrase(judge, answer, "answer_cheapest", 'Hung Fook Tong')
    check_answer_money(judge, answer, "answer_cheapest_price", 1.15)
    check_answer_phrase(judge, answer, "answer_most_booked", 'Top-Rated Hong Kong Tour')
    check_answer_number(judge, answer, "answer_reviews", '27')
    check_answer_number(judge, answer, "answer_booked_count", '610')
    check_answer_money(judge, answer, "answer_total_paid", 153.04)
    check_rows_added(judge, initial_db, after_db, 'attraction_bookings',
                      [['rx:^TA', 94229569, 41, None, '2026-10-12', 2, 'Leo', 'Ng', 'leo.ng@example.com', 153.04, 'confirmed', None]], 'attraction_booking_created')
    check_only_tables_changed(judge, initial_db, after_db, {'attraction_bookings'})


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
