#!/usr/bin/env python3
"""Verify Trip.com--6.

Alice: 480 Trip Coins, hotel THALICE1 at Harrah's Las Vegas (check-in 16:00), flight TFALICE1 SFO->JFK out 22:15 / return 11:35; wishlist 3 saved (priciest $327); FLYTRIP10 min $150; nonstop rebooking on the route $205+$228=$433; cancel the more expensive booking (the flight, $422).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_any, check_answer_count_at_least,
                        check_answer_money, check_answer_number, check_answer_phrase,
                        check_only_tables_changed, check_read_only,
                        check_rows_added, check_rows_changed, check_seed_contract,
                        check_set_delta, check_screenshots, check_trajectory_identity,
                        check_visited_any, check_visited_path, final_answer, run_verifier)

TASK_ID = "Trip.com--6"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_sign_in", r"/sign-in/")
    check_visited_path(judge, traj, "visited_account", r"/account/")
    check_visited_path(judge, traj, "visited_bookings", r"/account/bookings")
    check_visited_path(judge, traj, "visited_hotel_page", r"/hotels/detail/718690")
    check_visited_any(judge, traj, "visited_cancel", ['/bookings/cancel/flight/TFALICE1', '/account/bookings'])
    check_answer_number(judge, answer, "answer_coins", '480')
    check_answer_phrase(judge, answer, "answer_hotel", 'Harrah')
    check_answer_phrase(judge, answer, "answer_checkin_time", '16:00')
    check_answer_any(judge, answer, "answer_route", ['SFO', 'San Francisco'])
    check_answer_phrase(judge, answer, "answer_outbound_time", '22:15')
    check_answer_phrase(judge, answer, "answer_cancelled_ref", 'TFALICE1')
    check_answer_phrase(judge, answer, "answer_flight_status", 'cancelled')
    check_answer_phrase(judge, answer, "answer_hotel_status", 'confirmed')
    check_answer_number(judge, answer, "answer_wishlist_count", '3')
    check_answer_number(judge, answer, "answer_priciest", '327')
    check_answer_number(judge, answer, "answer_promo_min", '150')
    check_answer_money(judge, answer, "answer_rebook_total", 433.0)
    check_rows_changed(judge, initial_db, after_db, 'flight_bookings',
                       [['TFALICE1', 1, 2, 1, 'Alice', 'Johnson', 'alice.j@test.com', 'rx:\\+1 555 010 0000', 'Economy', 'rt', 422.0, '', 'cancelled', None]], 'flight_cancelled')
    check_only_tables_changed(judge, initial_db, after_db, {'flight_bookings'})


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
