#!/usr/bin/env python3
"""Verify Trip.com--16.

Paris Las Vegas two nights 5-7 Oct in the cheapest room: $167 nightly, $22 taxes/fees per night, $378 grand total; room sleeps 2, 1 king or 2 queen, free cancellation before 11:59 PM Oct 1; second-cheapest room Bordeaux Room King grand total $388; cheapest room one-night total 5-6 Oct $189; hotel 8.6 with 805 reviews; site search shows Bellagio at $467. Read-only (booking forms opened to confirm, no booking made).

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_any, check_answer_count_at_least,
                        check_answer_money, check_answer_number, check_answer_phrase,
                        check_only_tables_changed, check_read_only,
                        check_rows_added, check_rows_changed, check_seed_contract,
                        check_set_delta, check_screenshots, check_trajectory_identity,
                        check_visited_any, check_visited_path, final_answer, run_verifier)

TASK_ID = "Trip.com--16"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_search", r"/search\?")
    check_visited_path(judge, traj, "visited_hotel_detail", r"/hotels/detail/733090")
    check_visited_path(judge, traj, "visited_book_form", r"/hotels/book/(22|24)")
    check_answer_money(judge, answer, "answer_nightly", 167.0)
    check_answer_money(judge, answer, "answer_taxes_per_night", 22.0)
    check_answer_money(judge, answer, "answer_grand_total", 378.0)
    check_answer_phrase(judge, answer, "answer_room", 'Room Type Assigned On Arrival')
    check_answer_phrase(judge, answer, "answer_bed", '1 king bed or 2 queen beds')
    check_answer_number(judge, answer, "answer_sleeps", '2')
    check_answer_phrase(judge, answer, "answer_cancel_deadline", '11:59 PM, Oct 1')
    check_answer_phrase(judge, answer, "answer_second_room", 'Bordeaux Room King')
    check_answer_money(judge, answer, "answer_second_total", 388.0)
    check_answer_money(judge, answer, "answer_onenight_total", 189.0)
    check_answer_number(judge, answer, "answer_score", '8.6')
    check_answer_number(judge, answer, "answer_reviews", '805')
    check_answer_phrase(judge, answer, "answer_bellagio", 'Bellagio')
    check_answer_money(judge, answer, "answer_bellagio_rate", 467.0)
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
