#!/usr/bin/env python3
"""Verify Trip.com--15.

David: 480 Trip Coins; bookings Harrah's Las Vegas Nov 1-3 $136 (136 Trip Coins) + Orlando Go City Explorer Pass Nov 2 $121.68; hotel page: 8.4, 3-star, Las Vegas Strip, check-in 16:00, cheapest room $56; that room's repeat two-night total 18-20 Nov $128.00; booked activity found via site search (highlights: choose 2 to 5 attractions); wishlist 3 saved; ACTIVITY15 min $50. Read-only.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_any, check_answer_count_at_least,
                        check_answer_money, check_answer_number, check_answer_phrase,
                        check_only_tables_changed, check_read_only,
                        check_rows_added, check_rows_changed, check_seed_contract,
                        check_set_delta, check_screenshots, check_trajectory_identity,
                        check_visited_any, check_visited_path, final_answer, run_verifier)

TASK_ID = "Trip.com--15"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_sign_in", r"/sign-in/")
    check_visited_path(judge, traj, "visited_account", r"/account/")
    check_visited_path(judge, traj, "visited_bookings", r"/account/bookings")
    check_visited_path(judge, traj, "visited_hotel_page", r"/hotels/detail/718690")
    check_visited_path(judge, traj, "visited_repeat_form", r"/hotels/book/1")
    check_visited_path(judge, traj, "visited_search", r"/search\?")
    check_visited_path(judge, traj, "visited_activity_detail", r"/things-to-do/detail/110625321")
    check_visited_path(judge, traj, "visited_wishlist", r"/account/wishlist")
    check_visited_path(judge, traj, "visited_coupons", r"/account/coupons")
    check_answer_number(judge, answer, "answer_coins", '480')
    check_answer_phrase(judge, answer, "answer_hotel_booking", 'Harrah')
    check_answer_phrase(judge, answer, "answer_hotel_dates", 'Nov 1')
    check_answer_money(judge, answer, "answer_hotel_total", 136.0)
    check_answer_phrase(judge, answer, "answer_attraction_booking", 'Go City Explorer Pass')
    check_answer_money(judge, answer, "answer_attraction_total", 121.68)
    check_answer_number(judge, answer, "answer_stars", '3')
    check_answer_phrase(judge, answer, "answer_area", 'Las Vegas Strip')
    check_answer_phrase(judge, answer, "answer_cheapest_room", 'Room Type Assigned On Arrival')
    check_answer_number(judge, answer, "answer_room_price", '56')
    check_answer_number(judge, answer, "answer_coins_earned", '136')
    check_answer_phrase(judge, answer, "answer_checkin_time", '16:00')
    check_answer_money(judge, answer, "answer_repeat_total", 128.0)
    check_answer_phrase(judge, answer, "answer_highlights_choose", 'Choose 2 to 5')
    check_answer_number(judge, answer, "answer_wishlist_count", '3')
    check_answer_phrase(judge, answer, "answer_coupon", 'ACTIVITY15')
    check_answer_number(judge, answer, "answer_coupon_min", '50')
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
