#!/usr/bin/env python3
"""Verify Trip.com--11.

Carol: 480 Trip Coins; two cheapest bookable Miami hotels: Hyatt Place Miami Airport East (8.3, $93; cheapest room $93/$105 incl. taxes, $1.05 Trip Coins, 1 king bed and 1 sofa bed) and Kompose Boutique Hotel Miami Airport (8.3, $100; cheapest room $82); wishlist 3 saved; highest-minimum coupon SAVE25 ($200). Read-only.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_any, check_answer_count_at_least,
                        check_answer_money, check_answer_number, check_answer_phrase,
                        check_only_tables_changed, check_read_only,
                        check_rows_added, check_rows_changed, check_seed_contract,
                        check_set_delta, check_screenshots, check_trajectory_identity,
                        check_visited_any, check_visited_path, final_answer, run_verifier)

TASK_ID = "Trip.com--11"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_screenshots(judge, traj)
    check_visited_path(judge, traj, "visited_sign_in", r"/sign-in/")
    check_visited_path(judge, traj, "visited_account", r"/account/")
    check_visited_path(judge, traj, "visited_hotel_list", r"/hotels/list\?")
    check_visited_path(judge, traj, "visited_hotel_detail", r"/hotels/detail/4648397")
    check_visited_path(judge, traj, "visited_runnerup_detail", r"/hotels/detail/68493916")
    check_visited_path(judge, traj, "visited_wishlist", r"/account/wishlist")
    check_visited_path(judge, traj, "visited_coupons", r"/account/coupons")
    check_answer_number(judge, answer, "answer_coins", '480')
    check_answer_phrase(judge, answer, "answer_hotel", 'Hyatt Place Miami Airport East')
    check_answer_number(judge, answer, "answer_score", '8.3')
    check_answer_any(judge, answer, "answer_room_name", ['King Room', 'Accessible King Bed/Tub', 'Accessible King Room With Sofa Bed'])
    check_answer_phrase(judge, answer, "answer_bed", '1 king bed and 1 sofa bed')
    check_answer_money(judge, answer, "answer_room_total", 105.0)
    check_answer_money(judge, answer, "answer_coins_earned", 1.05)
    check_answer_phrase(judge, answer, "answer_runnerup", 'Kompose')
    check_answer_number(judge, answer, "answer_runnerup_score", '8.3')
    check_answer_money(judge, answer, "answer_runnerup_price", 100.0)
    check_answer_phrase(judge, answer, "answer_runnerup_room", 'King Room')
    check_answer_money(judge, answer, "answer_runnerup_room_price", 82.0)
    check_answer_number(judge, answer, "answer_wishlist_count", '3')
    check_answer_phrase(judge, answer, "answer_coupon", 'SAVE25')
    check_answer_number(judge, answer, "answer_coupon_min", '200')
    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
