#!/usr/bin/env python3
"""Verify Student.com--5.

Gainesville internship listings: total count, newest posting, part-timeand fellowship tag counts, the Part-Time filter's job, the footer Jobspage's newest Austin listing, and the Gainesville city page propertycount.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_bookmark_delta, check_enquiry_created,
                        check_only_tables_changed, check_read_only,
                        check_trajectory_identity, check_user_created,
                        check_views_added, check_views_only, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Student.com--5"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_visited_path(judge, traj, "visited_gainesville_jobs", r"/us/fl/gainesville/internships")
    check_visited_path(judge, traj, "visited_jobs_parttime_filter", r"/us/fl/gainesville/internships\?type=part-time")
    check_visited_path(judge, traj, "visited_jobs_home", r"/jobs")
    check_visited_path(judge, traj, "visited_gainesville_city", r"/us/fl/gainesville")
    check_answer_number(judge, answer, "answer_total", 5)
    check_answer_phrase(judge, answer, "answer_newest_title", 'Medical Assistant')
    check_answer_phrase(judge, answer, "answer_newest_company", 'Theoriamedical')
    check_answer_number(judge, answer, "answer_parttime", 1)
    check_answer_number(judge, answer, "answer_fellowship", 3)
    check_answer_phrase(judge, answer, "answer_filtered_title", 'Part-Time Assistant Manager - Level 2')
    check_answer_phrase(judge, answer, "answer_filtered_company", 'Boxlunch')
    check_answer_phrase(judge, answer, "answer_austin_newest", 'Operations Associate (Part-Time) - Domain Austin')
    check_answer_phrase(judge, answer, "answer_austin_company", 'Aloyoga')
    check_answer_number(judge, answer, "answer_gainesville_properties", 15)

    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
