#!/usr/bin/env python3
"""Verify Student.com--19.

Alice's full account audit: the older inquiry (reference, property,date, message), the other inquiry's reference and property, allsaved-property names and the total, and the Recently Viewed count.

Generated by make_verifiers.py (deterministic regeneration; do not edit by hand).
"""
from verify_lib import (check_answer_absent, check_answer_any,
                        check_answer_count_at_least, check_answer_number,
                        check_answer_phrase, check_bookmark_delta, check_enquiry_created,
                        check_only_tables_changed, check_read_only,
                        check_trajectory_identity, check_user_created,
                        check_views_added, check_views_only, check_visited_path,
                        final_answer, run_verifier)

TASK_ID = "Student.com--19"


def run_checks(judge, traj, initial_db, after_db):
    answer = final_answer(traj)
    check_trajectory_identity(judge, traj, TASK_ID)
    check_visited_path(judge, traj, "visited_inquiries", r"/profile/inquiries")
    check_visited_path(judge, traj, "visited_bookmarks", r"/profile/bookmarks")
    check_visited_path(judge, traj, "visited_history", r"/profile/history")
    check_answer_phrase(judge, answer, "answer_reference", 'INQ-000001')
    check_answer_phrase(judge, answer, "answer_property", 'Moontower')
    check_answer_any(judge, answer, "answer_date", ['September 20, 2026', 'September 20', '2026-09-20'])
    check_answer_phrase(judge, answer, "answer_message", 'studio with a private bathroom')
    check_answer_number(judge, answer, "answer_saved_count", 3)
    check_answer_phrase(judge, answer, "answer_other_reference", 'INQ-000002')
    check_answer_phrase(judge, answer, "answer_other_property", 'Villas on Rio')
    check_answer_phrase(judge, answer, "answer_saved_name_3", 'International House')
    check_answer_number(judge, answer, "answer_viewed_count", 4)

    check_read_only(judge, initial_db, after_db)


if __name__ == "__main__":
    raise SystemExit(run_verifier(TASK_ID, run_checks))
